include:
  - board: xiao_ble/nrf52840
    shield: mapadubu_left
    snippet: studio-rpc-usb-uart zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: xiao_ble/nrf52840
    shield: mapadubu_right
  - board: xiao_ble/nrf52840
    shield: settings_reset
# there is no settingsreset (needed) for the XIAO
