include:
  - board: nice_nano
    shield: mapadubu_left
    snippet: studio-rpc-usb-uart zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano
    shield: mapadubu_right
# there is no settingsreset (needed) for the XIAO
